all: main1.exe main2.exe

main1.exe: main1.c DynamicArray.o
	gcc main1.c DynamicArray.o -o main1.exe

main2.exe: main2.c DynamicArray.o
	gcc main2.c DynamicArray.o -o main2.exe

DynamicArray.o: DynamicArray.c DynamicArray.h util.h
	gcc -c DynamicArray.c -o DynamicArray.o

clean:
	del /q *.o *.exe